const List<Map<String, String>> asmaUlHusnaData = [
  {"id": "1", "arabic": "ٱلْرَّحْمَـانُ", "transliteration": "AR-RAHMAN", "translation": "The Beneficent"},
  {"id": "2", "arabic": "ٱلْرَّحِيْمُ", "transliteration": "AR-RAHIM", "translation": "The Merciful"},
  {"id": "3", "arabic": "ٱلْمَلِكُ", "transliteration": "AL-MALIK", "translation": "The King"},
  {"id": "4", "arabic": "ٱلْقُدُّوسُ", "transliteration": "AL-QUDDUS", "translation": "The Most Holy"},
  {"id": "5", "arabic": "ٱلْسَّلَامُ", "transliteration": "AS-SALAM", "translation": "The Source of Peace"},
  {"id": "6", "arabic": "ٱلْمُؤْمِنُ", "transliteration": "AL-MU'MIN", "translation": "The Guardian of Faith"},
  {"id": "7", "arabic": "ٱلْمُهَيْمِنُ", "transliteration": "AL-MUHAYMIN", "translation": "The Protector"},
  {"id": "8", "arabic": "ٱلْعَزِيْزُ", "transliteration": "AL-AZIZ", "translation": "The Mighty"},
  {"id": "9", "arabic": "ٱلْجَبَّارُ", "transliteration": "AL-JABBAR", "translation": "The Compeller"},
  {"id": "10", "arabic": "ٱلْمُتَكَبِّرُ", "transliteration": "AL-MUTAKABBIR", "translation": "The Majestic"},
  {"id": "11", "arabic": "ٱلْخَالِقُ", "transliteration": "AL-KHALIQ", "translation": "The Creator"},
  {"id": "12", "arabic": "ٱلْبَارِئُ", "transliteration": "AL-BARI'", "translation": "The Evolver"},
  {"id": "13", "arabic": "ٱلْمُصَوِّرُ", "transliteration": "AL-MUSAWWIR", "translation": "The Fashioner"},
  {"id": "14", "arabic": "ٱلْغَفَّارُ", "transliteration": "AL-GHAFFAR", "translation": "The Great Forgiver"},
  {"id": "15", "arabic": "ٱلْقَهَّارُ", "transliteration": "AL-QAHHAR", "translation": "The All-Dominant"},
  {"id": "16", "arabic": "ٱلْوَهَّابُ", "transliteration": "AL-WAHHAB", "translation": "The Bestower"},
  {"id": "17", "arabic": "ٱلْرَّزَّاقُ", "transliteration": "AR-RAZZAQ", "translation": "The Provider"},
  {"id": "18", "arabic": "ٱلْفَتَّاحُ", "transliteration": "AL-FATTAH", "translation": "The Opener"},
  {"id": "19", "arabic": "ٱلْعَلِيْمُ", "transliteration": "AL-'ALIM", "translation": "The All-Knowing"},
  {"id": "20", "arabic": "ٱلْقَابِضُ", "transliteration": "AL-QABID", "translation": "The Restrainer"},
  {"id": "21", "arabic": "ٱلْبَاسِطُ", "transliteration": "AL-BASIT", "translation": "The Expander"},
  {"id": "22", "arabic": "ٱلْخَافِضُ", "transliteration": "AL-KHAFID", "translation": "The Abaser"},
  {"id": "23", "arabic": "ٱلْرَّافِعُ", "transliteration": "AR-RAFI'", "translation": "The Exalter"},
  {"id": "24", "arabic": "ٱلْمُعِزُّ", "transliteration": "AL-MU'IZZ", "translation": "The Giver of Honor"},
  {"id": "25", "arabic": "ٱلْمُذِلُّ", "transliteration": "AL-MUDHILL", "translation": "The Giver of Dishonor"},
  {"id": "26", "arabic": "ٱلْسَّمِيْعُ", "transliteration": "AS-SAMI'", "translation": "The All-Hearing"},
  {"id": "27", "arabic": "ٱلْبَصِيْرُ", "transliteration": "AL-BASIR", "translation": "The All-Seeing"},
  {"id": "28", "arabic": "ٱلْحَكَمُ", "transliteration": "AL-HAKAM", "translation": "The Judge"},
  {"id": "29", "arabic": "ٱلْعَدْلُ", "transliteration": "AL-'ADL", "translation": "The Just"},
  {"id": "30", "arabic": "ٱلْلَّطِيْفُ", "transliteration": "AL-LATIF", "translation": "The Subtle One"},
  {"id": "31", "arabic": "ٱلْخَبِيْرُ", "transliteration": "AL-KHABIR", "translation": "The All-Aware"},
  {"id": "32", "arabic": "ٱلْحَلِيْمُ", "transliteration": "AL-HALIM", "translation": "The Forbearing"},
  {"id": "33", "arabic": "ٱلْعَظِيْمُ", "transliteration": "AL-AZIM", "translation": "The Magnificent"},
  {"id": "34", "arabic": "ٱلْغَفُوْرُ", "transliteration": "AL-GHAFUR", "translation": "The All-Forgiving"},
  {"id": "35", "arabic": "ٱلْشَّكُوْرُ", "transliteration": "ASH-SHAKUR", "translation": "The Grateful"},
  {"id": "36", "arabic": "ٱلْعَلِيُّ", "transliteration": "AL-ALI", "translation": "The Most High"},
  {"id": "37", "arabic": "ٱلْكَبِيْرُ", "transliteration": "AL-KABIR", "translation": "The Great"},
  {"id": "38", "arabic": "ٱلْحَفِيْظُ", "transliteration": "AL-HAFIZ", "translation": "The Preserver"},
  {"id": "39", "arabic": "ٱلْمُقِيْتُ", "transliteration": "AL-MUQIT", "translation": "The Sustainer"},
  {"id": "40", "arabic": "ٱلْحَسِيْبُ", "transliteration": "AL-HASIB", "translation": "The Reckoner"},
  {"id": "41", "arabic": "ٱلْجَلِيْلُ", "transliteration": "AL-JALIL", "translation": "The Majestic"},
  {"id": "42", "arabic": "ٱلْكَرِيْمُ", "transliteration": "AL-KARIM", "translation": "The Generous"},
  {"id": "43", "arabic": "ٱلْرَّقِيْبُ", "transliteration": "AR-RAQIB", "translation": "The Watchful"},
  {"id": "44", "arabic": "ٱلْمُجِيْبُ", "transliteration": "AL-MUJIB", "translation": "The Responsive"},
  {"id": "45", "arabic": "ٱلْوَاسِعُ", "transliteration": "AL-WASI'", "translation": "The All-Embracing"},
  {"id": "46", "arabic": "ٱلْحَكِيْمُ", "transliteration": "AL-HAKIM", "translation": "The Wise"},
  {"id": "47", "arabic": "ٱلْوَدُوْدُ", "transliteration": "AL-WADUD", "translation": "The Loving"},
  {"id": "48", "arabic": "ٱلْمَجِيْدُ", "transliteration": "AL-MAJID", "translation": "The Glorious"},
  {"id": "49", "arabic": "ٱلْبَاعِثُ", "transliteration": "AL-BA'ITH", "translation": "The Resurrector"},
  {"id": "50", "arabic": "ٱلْشَّهِيْدُ", "transliteration": "ASH-SHAHID", "translation": "The Witness"},
  {"id": "51", "arabic": "ٱلْحَقُّ", "transliteration": "AL-HAQQ", "translation": "The Truth"},
  {"id": "52", "arabic": "ٱلْوَكِيْلُ", "transliteration": "AL-WAKIL", "translation": "The Trustee"},
  {"id": "53", "arabic": "ٱلْقَوِيُّ", "transliteration": "AL-QAWI", "translation": "The Strong"},
  {"id": "54", "arabic": "ٱلْمَتِيْنُ", "transliteration": "AL-MATIN", "translation": "The Firm"},
  {"id": "55", "arabic": "ٱلْوَلِيُّ", "transliteration": "AL-WALI", "translation": "The Friend"},
  {"id": "56", "arabic": "ٱلْحَمِيْدُ", "transliteration": "AL-HAMID", "translation": "The Praiseworthy"},
  {"id": "57", "arabic": "ٱلْمُحْصِيُ", "transliteration": "AL-MUHSI", "translation": "The Accounter"},
  {"id": "58", "arabic": "ٱلْمُبْدِئُ", "transliteration": "AL-MUBDI'", "translation": "The Originator"},
  {"id": "59", "arabic": "ٱلْمُعِيْدُ", "transliteration": "AL-MU'ID", "translation": "The Restorer"},
  {"id": "60", "arabic": "ٱلْمُحْيِيُ", "transliteration": "AL-MUHYI", "translation": "The Giver of Life"},
  {"id": "61", "arabic": "ٱلْمُمِيْتُ", "transliteration": "AL-MUMIT", "translation": "The Taker of Life"},
  {"id": "62", "arabic": "ٱلْحَيُّ", "transliteration": "AL-HAYY", "translation": "The Ever-Living"},
  {"id": "63", "arabic": "ٱلْقَيُّوْمُ", "transliteration": "AL-QAYYUM", "translation": "The Self-Subsisting"},
  {"id": "64", "arabic": "ٱلْوَاجِدُ", "transliteration": "AL-WAJID", "translation": "The Perceiver"},
  {"id": "65", "arabic": "ٱلْمَاجِدُ", "transliteration": "AL-MAJID", "translation": "The Illustrious"},
  {"id": "66", "arabic": "ٱلْوَاحِدُ", "transliteration": "AL-WAHID", "translation": "The One"},
  {"id": "67", "arabic": "ٱلْأَحَدُ", "transliteration": "AL-AHAD", "translation": "The Unique"},
  {"id": "68", "arabic": "ٱلْصَّمَدُ", "transliteration": "AS-SAMAD", "translation": "The Eternal"},
  {"id": "69", "arabic": "ٱلْقَادِرُ", "transliteration": "AL-QADIR", "translation": "The Able"},
  {"id": "70", "arabic": "ٱلْمُقْتَدِرُ", "transliteration": "AL-MUQTADIR", "translation": "The All-Powerful"},
  {"id": "71", "arabic": "ٱلْمُقَدِّمُ", "transliteration": "AL-MUQADDIM", "translation": "The Expediter"},
  {"id": "72", "arabic": "ٱلْمُؤَخِّرُ", "transliteration": "AL-MU'AKHKHIR", "translation": "The Delayer"},
  {"id": "73", "arabic": "ٱلْأَوَّلُ", "transliteration": "AL-AWWAL", "translation": "The First"},
  {"id": "74", "arabic": "ٱلْآخِرُ", "transliteration": "AL-AKHIR", "translation": "The Last"},
  {"id": "75", "arabic": "ٱلْظَّاهِرُ", "transliteration": "AZ-ZAHIR", "translation": "The Manifest"},
  {"id": "76", "arabic": "ٱلْبَاطِنُ", "transliteration": "AL-BATIN", "translation": "The Hidden"},
  {"id": "77", "arabic": "ٱلْوَالِي", "transliteration": "AL-WALI", "translation": "The Governor"},
  {"id": "78", "arabic": "ٱلْمُتَعَالِي", "transliteration": "AL-MUTA'ALI", "translation": "The Most Exalted"},
  {"id": "79", "arabic": "ٱلْبَرُّ", "transliteration": "AL-BARR", "translation": "The Source of All Goodness"},
  {"id": "80", "arabic": "ٱلْتَّوَّابُ", "transliteration": "AT-TAWWAB", "translation": "The Acceptor of Repentance"},
  {"id": "81", "arabic": "ٱلْمُنْتَقِمُ", "transliteration": "AL-MUNTAQIM", "translation": "The Avenger"},
  {"id": "82", "arabic": "ٱلْعَفُوُّ", "transliteration": "AL-'AFUW", "translation": "The Pardoner"},
  {"id": "83", "arabic": "ٱلْرَّؤُوْفُ", "transliteration": "AR-RA'UF", "translation": "The Compassionate"},
  {"id": "84", "arabic": "مَالِكُ ٱلْمُلْكُ", "transliteration": "MALIK-UL-MULK", "translation": "The Owner of Sovereignty"},
  {"id": "85", "arabic": "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ", "transliteration": "DHUL-JALALI WAL-IKRAM", "translation": "The Lord of Majesty and Bounty"},
  {"id": "86", "arabic": "ٱلْمُقْسِطُ", "transliteration": "AL-MUQSIT", "translation": "The Equitable"},
  {"id": "87", "arabic": "ٱلْجَامِعُ", "transliteration": "AL-JAMI'", "translation": "The Gatherer"},
  {"id": "88", "arabic": "ٱلْغَنِيُّ", "transliteration": "AL-GHANI", "translation": "The Self-Sufficient"},
  {"id": "89", "arabic": "ٱلْمُغْنِيُ", "transliteration": "AL-MUGHNI", "translation": "The Enricher"},
  {"id": "90", "arabic": "ٱلْمَانِعُ", "transliteration": "AL-MANI'", "translation": "The Preventer"},
  {"id": "91", "arabic": "ٱلْضَّارُ", "transliteration": "AD-DARR", "translation": "The Distresser"},
  {"id": "92", "arabic": "ٱلْنَّافِعُ", "transliteration": "AN-NAFI'", "translation": "The Propitious"},
  {"id": "93", "arabic": "ٱلْنُّورُ", "transliteration": "AN-NUR", "translation": "The Light"},
  {"id": "94", "arabic": "ٱلْهَادِي", "transliteration": "AL-HADI", "translation": "The Guide"},
  {"id": "95", "arabic": "ٱلْبَدِيْعُ", "transliteration": "AL-BADI'", "translation": "The Incomparable"},
  {"id": "96", "arabic": "ٱلْبَاقِي", "transliteration": "AL-BAQI", "translation": "The Everlasting"},
  {"id": "97", "arabic": "ٱلْوَارِثُ", "transliteration": "AL-WARITH", "translation": "The Supreme Inheritor"},
  {"id": "98", "arabic": "ٱلْرَّشِيْدُ", "transliteration": "AR-RASHID", "translation": "The Guide to the Right Path"},
  {"id": "99", "arabic": "ٱلْصَّبُوْرُ", "transliteration": "AS-SABUR", "translation": "The Patient"}
];